# Variabel

Diketahui beberapa list berikut:   
1. ipk = [3.05, 3.45, 3.33, 2.90, 3.10, 3.23, 3.80, 3.74, 3.67, 3.39, 3.41, 3.51, 3.21, 3.55, 3.34, 3.67, 3.77, 3.00, 3.25, 2.78]   
2. sks = [88, 89, 90, 100, 80, 78, 90, 90, 92, 97, 95, 80, 88, 102, 87, 84, 85, 89, 101, 80]
3. konsentrasi = konsentrasi = ["AK", "AK", "DS", "DS", "AK", "AK", "MK", "MK", "DS", "DS", "IN", "IN", "BS", "BS", "MK", "MK", "BS", "BS", "IN", "IN"]

In [103]:
# definisi variabel
ipk = [3.05, 3.45, 3.33, 2.90, 3.10, 3.23, 3.80, 3.74, 3.67, 3.39, 3.41, 3.51, 3.21, 3.55, 3.34, 3.67, 3.77, 3.00, 3.25, 2.78]
sks = [88, 89, 90, 100, 80, 78, 90, 90, 92, 97, 95, 80, 88, 102, 87, 84, 85, 89, 101, 80]
konsentrasi = ["AK", "AK", "DS", "DS", "AK", "AK", "MK", "MK", "DS", "DS", "IN", "IN", "BS", "BS", "MK", "MK", "BS", "BS", "IN", "IN"]

In [ ]:
# panjang dari setiap variabel


In [104]:
# diperoleh nilai mata kuliah baru dengan bobot yang tersimpan dalam variabel bobot berikut
bobot = [3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0]
print(bobot)

[3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0]


In [121]:
# sks mata kuliah tersebut adalah 3. Hitung total bobot dengan mengalikan list bobot dengan 3. Simpan dalam variabel tot_bobot
tot_bobot = bobot*3


In [122]:
# print out tot_bobot
print(tot_bobot)

[3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0, 3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0, 3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0]


### apakah hasilnya sesuai yang diinginkan? 

# Menggunakan package numpy

Digunakan untuk manipulasi array secara mudah dan cepat. Daftar fungsi yang dapat digunakan dalam library numpy dapat diakses di [Numpy Array Manipulation](https://www.tutorialspoint.com/numpy/numpy_array_manipulation.htm). NumPy bekerja dengan array yang disebut ndarray. Dimensi array adalah tingkatan kedalaman dari suatu array. 



In [1]:
# import numpy sebagai np
import numpy as np

### 1. Membuat N-Dimensional Array

In [ ]:
# Membuat 0-D Array

a = np.array(23)
print(a)

In [ ]:
# Membuat 1-D array

b = np.array([1, 4, 6, 9])
print(b)

In [ ]:
# Membuat 2-D array

c = np.array([[2, 3, 5], [7, 11, 13]])
print(c)

In [ ]:
# Membuat 3-D array

d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(d)

In [ ]:
# Membuat n-D array dengan numpy.array(array, ndmin = n)

e = np.array([[1, 2, 3], [4, 5, 6]], ndmin = 5)
print(e)

In [ ]:
# Mengecek dimensi array dengan ndim

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

### 2. Indeks Array

Indeks array pada dasarnya digunakan untuk memanggil elemen di dalam array. 

In [124]:
# Memanggil elemen pertama pada 1-D array
print(b[0])

1


In [125]:
# Memanggil array pertama pada 2-D array
arr = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
print(arr[0])

[11 12 13]


In [126]:
# Memanggil elemen kedua pada array ketiga 2-D array

print(arr[2, 1])

18


### 3. Slicing Array

Slicing (memotong) maksudnya adalah mengambil elemen dari satu indeks ke indeks lain. Dengan kata lain, mengambil beberapa elemen. Slicing dapat dilakukan dengan menuliskan `[mulai : akhir]` atau `[mulai : akhir : langkah]`.   

- Jika `mulai` tidak dituliskan, maka dianggap 0
- Jika `akhir` tidak dituliskan, maka dianggap hingga panjang array
- Jika `langkah` tidak dituliskan, maka dianggap 1

In [ ]:
arr = np.array([12, 15, 17, 20, 23, 34, 56, 78, 100, 56, 88])

# Mengambil elemen kedua hingga keenam (15, 17, 20, 23, 34)
arr[1:6]

In [ ]:
arr = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]], ndmin=2)

# Mengambil array pertama dan kedua (indeks 0, 1) beserta elemen pertama dan kedua (indeks 0, 1)
arr[0:2, 0:2]

### 4. Menggabungkan

Menggabungkan (join) array. Gunakan `np.concatenate`

In [128]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([34, 56, 78, 90])

arr = np.concatenate((arr1, arr2))
print(arr)

[ 1  2  3  4 34 56 78 90]


In [130]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

# Jika axis = 0
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

print("\n")

# Jika axis = 1
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


#### Menggabungkan array dengan stack

Kita dapat melakukan penggabungan array pada axis yang baru dengan fungsi stack.

In [108]:
# Cobalah menggabungkan dua array berdimensi 1 berikut dengan stack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis = 0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [109]:
# Coba bandingkan apabila penggabungan dilakukan dengan menggunakan concatenate. Apa yang terjadi?
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2), axis = 0)

print(arr)

[1 2 3 4 5 6]


### 5. Random

Untuk merandim bilangan, kita import modul random dari numpy. 

In [3]:
from numpy import random

In [13]:
# Merandom bilangan bulat randint(low, high=None, size=None, dtype='l')


x = random.randint(10, 200, size = (4, 3))

print(x)

[[108  35  67]
 [127 112  70]
 [142 169 162]
 [148 166 199]]


In [5]:
x.ndim

2

In [132]:
# Merandom bilangan diantara 0 dan 1 rand(10)
x = random.rand(10)

print(x)

[0.02047438 0.41538629 0.73813623 0.70348313 0.06486392 0.00789082
 0.59261702 0.58642279 0.87479999 0.37658674]


In [133]:
? random.rand()

## Latihan

In [ ]:
# bentuklah array bobot, simpan dalam variabel np_bobot
np_bobot=np.array(None)
print(None)

In [ ]:
# Lakukan pengalian np_bobot dengan 3, simpan dalam tot_bobot. Print hasil tot_bobot
tot_bobot=None
print(None)

In [ ]:
# ubah ipk dan sks menjadi array, simpan dalam np_ipk dan np_sks
np_ipk = np.array(ipk)
np_sks = np.array(sks)

In [ ]:
# hitung ipk baru dengan penambahan nilai tersebut
np_ipk_new = None
print(np_ipk_new)

In [ ]:
# variabel mahasiswa
mahasiswa = [[3.05,88],[3.45,89],[3.33,90],[3.10,100],[3.23,80],[3.80,78],[3.74,90],[3.67,90],[3.39,92],[3.41,97],[3.51,95],[3.21,80],[3.55,88]]
print(type(mahasiswa))

In [ ]:
# ubah list mahasiswa dalam array, simpan dalam variabel np_mahasiswa
np_mahasiswa = np.array(None)
print(np_mahasiswa)

In [ ]:
# Berapakah ukuran array mahasiswa?
print(None)

In [ ]:
# tampilkan ipk dan sks mahasiswa ke 10
print(None)

In [ ]:
# tampilkan semua ipk
print(None)

In [ ]:
# tambahkan data baru ipk 3.45 dengan sks 102 dalam np_mahasiswa
np.append(np_mahasiswa, [[..., ...]], axis=0)

In [ ]:
# kurangkan semua elemen pada ipk dengan 0.2, dan tambahkan semua elemen pada sks dengan 3
np_mahasiswa + 

In [ ]:
# jadikan array konsentrasi
np_ipk = np.array(ipk)
np_sks = np.array(sks)
np_konsentrasi = np.array(konsentrasi)

In [ ]:
# print tipe dari np_konsentrasi
print(type(None))

In [ ]:
# sesuai dengan urutan, pilihlah ipk mahasiswa yang mengambil konsentrasi industri. Simpan dalam variabel industri
industri = None

# print variabel industri
print(industri)

In [ ]:
# sesuai dengan urutan, pilihlah ipk mahasiswa yang tidak mengambil industri. Simpan dalam variabel lain_industri
lain_industri = None

# print variabel lain_industri
print(lain_industri)

In [ ]:
print("Rata-rata ipk industri: "+str(None))
print("Rata-rata ipk bukan industri: "+str(None))